/*
Write CRUD endpoints for the accounts resource. Use the db object imported from data/dbConfig.js for database access via knex.
Manually test your endpoints with a REST client like Insomnia or Postman to check they are working as expected.

Accounts Schema
field	data type	metadata
id	unsigned integer	primary key, auto-increments, generated by database
name	string	required, unique
budget	numeric	required
*/

// Imports
const db = require('../data/dbConfig.js');