/*
Write CRUD endpoints for the accounts resource. Use the db object imported from data/dbConfig.js for database access via knex.
Manually test your endpoints with a REST client like Insomnia or Postman to check they are working as expected.

Accounts Schema
field	data type	metadata
id	unsigned integer	primary key, auto-increments, generated by database
name	string	required, unique
budget	numeric	required
*/

// Imports
const router = require('express').Router();
const db = require('../data/dbConfig.js');


// GET all accounts

// POST a new account
    // Validate post before adding

// PUT/UPDATE existing account
    // is validation needed before updating? 

// DELETE an exisitng account
    // is validation needed before updating? 

// Custom Middleware needed in order to validate the account.
    // name = string --> is required and unique**  
    // budget is a # --> also required

    
// Always export!
module.exports = router;